/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saegraphmap.window;

import java.awt.*;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import saegraphmap.linkedlist.TLieu;
import saegraphmap.linkedlist.TListe;
import saegraphmap.linkedlist.TRoute;
import saegraphmap.pathfinding.FloydWarshallMatrix;
import saegraphmap.window.listener.GraphPanelListener;

/**
 *
 * @author p2105876
 */
public class Mainscreen extends javax.swing.JFrame {

    /**
     * Creates new form Mainscreen
     */
    public Mainscreen() {
        initComponents();
        ImageIcon img = new ImageIcon("src/saegraphmap/data/logo.png");
        this.setIconImage(img.getImage());
        this.graphPanel1.addGraphPanelListener(new GraphListener());
        cbDeuxDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbunDistanceActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        globalOptionPanel = new javax.swing.JPanel();
        numberPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbVille = new javax.swing.JCheckBox();
        cbResto = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cbLoisir = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        cbDépartemental = new javax.swing.JCheckBox();
        cbAutoroute = new javax.swing.JCheckBox();
        cbNational = new javax.swing.JCheckBox();
        nbNoeud = new javax.swing.JLabel();
        nbRoute = new javax.swing.JLabel();
        neighborListPanel = new javax.swing.JPanel();
        neighborListPanel1 = new javax.swing.JPanel();
        cbunDistance = new javax.swing.JCheckBox();
        cbDeuxDistance = new javax.swing.JCheckBox();
        neighborListPanel2 = new javax.swing.JPanel();
        vcbville = new javax.swing.JCheckBox();
        vCbResto = new javax.swing.JCheckBox();
        vCbLoisir = new javax.swing.JCheckBox();
        comparPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        is2Distancetxt = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jScrollGraphpane = new javax.swing.JScrollPane();
        graphPanel1 = new saegraphmap.window.GraphPanel();
        pointDataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(970, 859));

        globalOptionPanel.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        numberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtres et nombre"));
        numberPanel.setEnabled(false);
        numberPanel.setMinimumSize(new java.awt.Dimension(0, 274));

        jLabel23.setText("Routes");

        cbVille.setSelected(true);
        cbVille.setText("Ville");
        cbVille.setEnabled(false);
        cbVille.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVilleItemStateChanged(evt);
            }
        });

        cbResto.setSelected(true);
        cbResto.setText("Restaurant");
        cbResto.setEnabled(false);
        cbResto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRestoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Noeud");

        cbLoisir.setSelected(true);
        cbLoisir.setText("Loisir");
        cbLoisir.setEnabled(false);
        cbLoisir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoisirItemStateChanged(evt);
            }
        });
        cbLoisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoisirActionPerformed(evt);
            }
        });

        cbDépartemental.setSelected(true);
        cbDépartemental.setText("Départemental");
        cbDépartemental.setEnabled(false);
        cbDépartemental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDépartementalItemStateChanged(evt);
            }
        });

        cbAutoroute.setSelected(true);
        cbAutoroute.setText("Autoroute");
        cbAutoroute.setEnabled(false);
        cbAutoroute.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAutorouteItemStateChanged(evt);
            }
        });

        cbNational.setSelected(true);
        cbNational.setText("National");
        cbNational.setEnabled(false);
        cbNational.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNationalItemStateChanged(evt);
            }
        });

        nbNoeud.setText("0");

        nbRoute.setText("0");

        javax.swing.GroupLayout numberPanelLayout = new javax.swing.GroupLayout(numberPanel);
        numberPanel.setLayout(numberPanelLayout);
        numberPanelLayout.setHorizontalGroup(
            numberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberPanelLayout.createSequentialGroup()
                .addGroup(numberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel7)
                    .addGroup(numberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(numberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(numberPanelLayout.createSequentialGroup()
                                .addGroup(numberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAutoroute)
                                    .addComponent(cbNational)
                                    .addComponent(cbDépartemental)
                                    .addComponent(cbVille)
                                    .addComponent(cbResto))
                                .addGap(0, 179, Short.MAX_VALUE))
                            .addGroup(numberPanelLayout.createSequentialGroup()
                                .addComponent(cbLoisir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nbNoeud))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numberPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nbRoute)))
                .addContainerGap())
        );
        numberPanelLayout.setVerticalGroup(
            numberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(cbVille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbResto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(numberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoisir)
                    .addComponent(nbNoeud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAutoroute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDépartemental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNational)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(nbRoute)
                .addContainerGap())
        );

        globalOptionPanel.add(numberPanel);

        neighborListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Voisins"));
        neighborListPanel.setEnabled(false);
        neighborListPanel.setLayout(new java.awt.BorderLayout());

        neighborListPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cbunDistance.setText("1-distance");
        cbunDistance.setEnabled(false);
        cbunDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbunDistanceActionPerformed(evt);
            }
        });
        neighborListPanel1.add(cbunDistance);

        cbDeuxDistance.setText("2-distance");
        cbDeuxDistance.setEnabled(false);
        neighborListPanel1.add(cbDeuxDistance);

        neighborListPanel.add(neighborListPanel1, java.awt.BorderLayout.PAGE_START);

        neighborListPanel2.setLayout(new java.awt.GridLayout(3, 0));

        vcbville.setSelected(true);
        vcbville.setText("Voir que les villes");
        vcbville.setEnabled(false);
        neighborListPanel2.add(vcbville);

        vCbResto.setSelected(true);
        vCbResto.setText("Voir que les retaurants");
        vCbResto.setEnabled(false);
        neighborListPanel2.add(vCbResto);

        vCbLoisir.setSelected(true);
        vCbLoisir.setText("Voir que les loisirs");
        vCbLoisir.setEnabled(false);
        neighborListPanel2.add(vCbLoisir);

        neighborListPanel.add(neighborListPanel2, java.awt.BorderLayout.CENTER);

        globalOptionPanel.add(neighborListPanel);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparaisons"));
        jPanel2.setEnabled(false);

        jLabel5.setText("caractere de la comparaison :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Aucun)", "Ouverture", "Gastronomie", "Culture" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Aucun lieu séléctionné");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 311, Short.MAX_VALUE)
            .addComponent(jLabel5)
            .addComponent(jLabel6)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout comparPanelLayout = new javax.swing.GroupLayout(comparPanel);
        comparPanel.setLayout(comparPanelLayout);
        comparPanelLayout.setHorizontalGroup(
            comparPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(comparPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(is2Distancetxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comparPanelLayout.setVerticalGroup(
            comparPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(is2Distancetxt)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        globalOptionPanel.add(comparPanel);

        getContentPane().add(globalOptionPanel, java.awt.BorderLayout.LINE_START);

        mainPanel.setBackground(java.awt.Color.white);
        mainPanel.setLayout(new java.awt.BorderLayout());

        jScrollGraphpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollGraphpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollGraphpane.setOpaque(false);
        jScrollGraphpane.setViewportView(graphPanel1);

        mainPanel.add(jScrollGraphpane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0);
        flowLayout1.setAlignOnBaseline(true);
        pointDataPanel.setLayout(flowLayout1);

        jLabel1.setText("Lieu séléctionné 1 (click)");
        pointDataPanel.add(jLabel1);

        jLabel11.setText("type:");
        pointDataPanel.add(jLabel11);

        jLabel13.setText("type");
        pointDataPanel.add(jLabel13);

        jLabel12.setText("Nom lieu:");
        pointDataPanel.add(jLabel12);

        jLabel14.setText("nom");
        pointDataPanel.add(jLabel14);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(new java.awt.Dimension(2, 17));
        jSeparator2.setName(""); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(2, 17));
        pointDataPanel.add(jSeparator2);

        jLabel2.setText("Lieu séléctionné 2 (shift + click)");
        pointDataPanel.add(jLabel2);

        jLabel32.setText("type:");
        pointDataPanel.add(jLabel32);

        jLabel33.setText("type");
        pointDataPanel.add(jLabel33);

        jLabel34.setText("Nom lieu:");
        pointDataPanel.add(jLabel34);

        jLabel35.setText("nom");
        pointDataPanel.add(jLabel35);

        jLabel3.setText("nombre de lieux:");
        pointDataPanel.add(jLabel3);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMinimumSize(new java.awt.Dimension(2, 17));
        jSeparator3.setName(""); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(2, 17));
        pointDataPanel.add(jSeparator3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("0");
        pointDataPanel.add(jLabel4);

        getContentPane().add(pointDataPanel, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Ouvrir un CSV");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator5);

        jMenuItem2.setText("Quitter...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Outils");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("afficher les nombres");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("afficher les informations");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("afficher les voisins");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("afficher les comparaisons");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem5);
        jMenu2.add(jSeparator6);

        jMenuItem10.setText("afficher tous les menus");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("afficher aucun menu");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        pointDataPanel.setVisible(true);
        neighborListPanel.setVisible(true);
        numberPanel.setVisible(true);
        jPanel2.setVisible(true);
        globalOptionPanel.setVisible(true);
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem5.setSelected(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        pointDataPanel.setVisible(false);
        neighborListPanel.setVisible(false);
        numberPanel.setVisible(false);
        jPanel2.setVisible(false);
        globalOptionPanel.setVisible(false);
        jCheckBoxMenuItem2.setSelected(false);
        jCheckBoxMenuItem3.setSelected(false);
        jCheckBoxMenuItem4.setSelected(false);
        jCheckBoxMenuItem5.setSelected(false);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        if (jCheckBoxMenuItem2.isSelected()){
            globalOptionPanel.setVisible(true);
            numberPanel.setVisible(true);
        }
        else numberPanel.setVisible(false);  
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        if (jCheckBoxMenuItem3.isSelected()){
            pointDataPanel.setVisible(true);
        }
        else pointDataPanel.setVisible(false);  
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
        if (jCheckBoxMenuItem4.isSelected()){
            neighborListPanel.setVisible(true);
        }
        else neighborListPanel.setVisible(false);  
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
        if (jCheckBoxMenuItem5.isSelected()){
            globalOptionPanel.setVisible(true);
            jPanel2.setVisible(true);
        }
        else jPanel2.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        comparaison();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cbVilleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVilleItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            fichier.changeLieuVisibility('V',true);
            System.out.println("1");
            nbNoeud.setText(Integer.toString(Integer.parseInt(nbNoeud.getText()) + fichier.compterVilles()));
        }
        else{
            fichier.changeLieuVisibility('V',false);
            System.out.println("2");
            nbNoeud.setText(Integer.toString(Integer.parseInt(nbNoeud.getText()) - fichier.compterVilles()));
        }
        graphPanel1.repaint();
    }//GEN-LAST:event_cbVilleItemStateChanged

    private void cbRestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRestoItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            fichier.changeLieuVisibility('R',true);
            nbNoeud.setText(Integer.toString(Integer.parseInt(nbNoeud.getText()) + fichier.compterRestaurants()));
        }
        else{
            fichier.changeLieuVisibility('R',false);
            nbNoeud.setText(Integer.toString(Integer.parseInt(nbNoeud.getText()) - fichier.compterRestaurants()));
        }
        graphPanel1.repaint();
    }//GEN-LAST:event_cbRestoItemStateChanged

    private void cbLoisirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoisirItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            fichier.changeLieuVisibility('L',true);
            nbNoeud.setText(Integer.toString(Integer.parseInt(nbNoeud.getText()) - fichier.compterLoisir()));
        }
        else{
            fichier.changeLieuVisibility('L',false);
            nbNoeud.setText(Integer.toString(Integer.parseInt(nbNoeud.getText()) - fichier.compterLoisir()));
        }
        graphPanel1.repaint();
    }//GEN-LAST:event_cbLoisirItemStateChanged

    private void cbDépartementalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDépartementalItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            graphPanel1.setAfficheDepartemental(true);;
            nbRoute.setText(Integer.toString(Integer.parseInt(nbRoute.getText()) + fichier.compterDepartementales()));
        }
        else{
            graphPanel1.setAfficheDepartemental(false);
            nbRoute.setText(Integer.toString(Integer.parseInt(nbRoute.getText()) - fichier.compterDepartementales()));
        }
        graphPanel1.repaint();
    }//GEN-LAST:event_cbDépartementalItemStateChanged

    private void cbAutorouteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAutorouteItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            graphPanel1.setAfficheAutoroute(true);
            nbRoute.setText(Integer.toString(Integer.parseInt(nbRoute.getText()) + fichier.compterAutoroute()));
        }
        else{
            graphPanel1.setAfficheAutoroute(false);
            nbRoute.setText(Integer.toString(Integer.parseInt(nbRoute.getText()) - fichier.compterAutoroute()));
        }
        graphPanel1.repaint();
    }//GEN-LAST:event_cbAutorouteItemStateChanged

    private void cbNationalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNationalItemStateChanged
    if(evt.getStateChange() == ItemEvent.SELECTED){
            graphPanel1.setAfficheNationale(true);
            nbRoute.setText(Integer.toString(Integer.parseInt(nbRoute.getText()) + fichier.compterNationales()));
        }
        else{
            graphPanel1.setAfficheNationale(false);
            nbRoute.setText(Integer.toString(Integer.parseInt(nbRoute.getText()) - fichier.compterNationales()));
        }
        graphPanel1.repaint();
    }//GEN-LAST:event_cbNationalItemStateChanged

    private void cbLoisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoisirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoisirActionPerformed

    private void cbunDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbunDistanceActionPerformed
        filtreUnDeuxDistance();
    }//GEN-LAST:event_cbunDistanceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        fc.setFileFilter(new FileNameExtensionFilter("CSV file", "csv"));
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String path = new String();
            path = file.getAbsolutePath();
            fichier = new TListe(path);
            graphPanel1.ajoutListePts(fichier);
            jScrollGraphpane.setViewportView(graphPanel1);
            Integer nombre = fichier.compterVilles() + fichier.compterRestaurants() + fichier.compterLoisir();      
            jLabel4.setText(nombre.toString());
            nbRoute.setText(Integer.toString(fichier.compterRoute()));
            nbNoeud.setText(Integer.toString(fichier.compterLieu()));
            numberPanel.setEnabled(true);
            for (Component c : numberPanel.getComponents()) c.setEnabled(true);
            comparPanel.setEnabled(false);
            for (Component c : comparPanel.getComponents()) c.setEnabled(false);
            neighborListPanel.setEnabled(false);
            for (Component c : neighborListPanel1.getComponents()) c.setEnabled(false);
            for (Component c : neighborListPanel2.getComponents()) c.setEnabled(false);
            }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbAutoroute;
    private javax.swing.JCheckBox cbDeuxDistance;
    private javax.swing.JCheckBox cbDépartemental;
    private javax.swing.JCheckBox cbLoisir;
    private javax.swing.JCheckBox cbNational;
    private javax.swing.JCheckBox cbResto;
    private javax.swing.JCheckBox cbVille;
    private javax.swing.JCheckBox cbunDistance;
    private javax.swing.JPanel comparPanel;
    private javax.swing.JPanel globalOptionPanel;
    private saegraphmap.window.GraphPanel graphPanel1;
    private javax.swing.JLabel is2Distancetxt;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollGraphpane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nbNoeud;
    private javax.swing.JLabel nbRoute;
    private javax.swing.JPanel neighborListPanel;
    private javax.swing.JPanel neighborListPanel1;
    private javax.swing.JPanel neighborListPanel2;
    private javax.swing.JPanel numberPanel;
    private javax.swing.JPanel pointDataPanel;
    private javax.swing.JCheckBox vCbLoisir;
    private javax.swing.JCheckBox vCbResto;
    private javax.swing.JCheckBox vcbville;
    // End of variables declaration//GEN-END:variables
    private FloydWarshallMatrix matrix;
    TListe fichier = null;
    TLieu selection1 = new TLieu();
    TLieu selection2 = new TLieu();

    private void comparaison(){
        if(jComboBox1.getSelectedItem()=="Ouverture") {
            jLabel6.setText(fichier.plusOuverte(selection1,selection2));
        }
        if(jComboBox1.getSelectedItem()=="Gastronomie") {
            jLabel6.setText(fichier.plusGastronomique(selection1,selection2));
        }
        if(jComboBox1.getSelectedItem()=="Culture") {
            jLabel6.setText(fichier.plusCulturelle(selection1,selection2));
        }
        if(jComboBox1.getSelectedItem()=="(Aucun)") {
            jLabel6.setText("aucun lieu séléctionné");
        }
    }

    private void filtreUnDeuxDistance(){
        if(cbunDistance.isSelected() || cbDeuxDistance.isSelected()) {
            ArrayList<TLieu> lieuAffiché = new ArrayList<>();
            lieuAffiché.add(selection1);
            if (cbunDistance.isSelected()) {
                if (vcbville.isSelected()) {
                    lieuAffiché.addAll(fichier.unDistance(selection1, 'V'));
                }
                if (vCbResto.isSelected()) {
                    lieuAffiché.addAll(fichier.unDistance(selection1, 'R'));
                }
                if (vCbLoisir.isSelected()) {
                    lieuAffiché.addAll(fichier.unDistance(selection1, 'L'));
                }
            }
            if (cbDeuxDistance.isSelected()) {
                if (vcbville.isSelected()) {
                    lieuAffiché.addAll(fichier.deuxDistance(selection1, 'V'));
                }
                if (vCbResto.isSelected()) {
                    lieuAffiché.addAll(fichier.deuxDistance(selection1, 'R'));
                }
                if (vCbLoisir.isSelected()) {
                    lieuAffiché.addAll(fichier.deuxDistance(selection1, 'L'));
                }
            }
            for (TLieu lieu = fichier.getListe(); lieu != null; lieu = lieu.getSuivant()) {
                if (lieuAffiché.contains(lieu)) {
                    lieu.getrJTogBtn().setVisible(true);
                } else {
                    lieu.getrJTogBtn().setVisible(false);
                }
            }
        }
        else {
            for (TLieu lieu = fichier.getListe(); lieu != null; lieu = lieu.getSuivant()) {
                lieu.getrJTogBtn().setVisible(true);
            }
        }
        graphPanel1.repaint();
    }

    class GraphListener implements GraphPanelListener{

        @Override
        public void lieuSelectedChanged(ArrayList<TLieu> lieuEvent) {
            if (lieuEvent.get(0) == null && lieuEvent.get(1) == null){
                jComboBox1.setEnabled(false);
                jLabel13.setText("");
                jLabel14.setText("non selectionne");
                jLabel33.setText("");
                jLabel35.setText("non selectionne");
                numberPanel.setEnabled(true);
                for (Component c : numberPanel.getComponents()) c.setEnabled(true);
                comparPanel.setEnabled(false);
                for (Component c : comparPanel.getComponents()) c.setEnabled(false);
                neighborListPanel.setEnabled(false);
                for (Component c : neighborListPanel1.getComponents()) c.setEnabled(false);
                for (Component c : neighborListPanel2.getComponents()) c.setEnabled(false);
                cbAutoroute.setSelected(true);
                cbDépartemental.setSelected(true);
                cbNational.setSelected(true);
                cbLoisir.setSelected(true);
                cbResto.setSelected(true);
                cbVille.setSelected(true);
                fichier.changeLieuVisibility('A',true);
                graphPanel1.repaint();
                is2Distancetxt.setText("");
            }
            else if (lieuEvent.get(0) == null && lieuEvent.get(1) != null){
                selection2 = lieuEvent.get(1);
                jComboBox1.setEnabled(false);
                jLabel13.setText("");
                jLabel14.setText("non selectionne");
                jLabel33.setText(Character.toString(selection2.getType()));
                jLabel35.setText(selection2.getNomLieu());
                numberPanel.setEnabled(true);
                for (Component c : numberPanel.getComponents()) c.setEnabled(true);
                comparPanel.setEnabled(false);
                for (Component c : comparPanel.getComponents()) c.setEnabled(false);
                neighborListPanel.setEnabled(false);
                for (Component c : neighborListPanel1.getComponents()) c.setEnabled(false);
                for (Component c : neighborListPanel2.getComponents()) c.setEnabled(false);
                cbAutoroute.setSelected(true);
                cbDépartemental.setSelected(true);
                cbNational.setSelected(true);
                cbLoisir.setSelected(true);
                cbResto.setSelected(true);
                cbVille.setSelected(true);
                fichier.changeLieuVisibility('A',true);
                graphPanel1.repaint();
                is2Distancetxt.setText("");
            }
            else if (lieuEvent.get(0) != null && lieuEvent.get(1) == null){
                selection1 = lieuEvent.get(0);
                jComboBox1.setEnabled(false);
                jLabel13.setText(Character.toString(selection1.getType()));
                jLabel14.setText(selection1.getNomLieu());
                jLabel33.setText("");
                jLabel35.setText("non selectionne");
                numberPanel.setEnabled(false);
                for (Component c : numberPanel.getComponents()) c.setEnabled(false);
                comparPanel.setEnabled(false);
                for (Component c : comparPanel.getComponents()) c.setEnabled(false);
                neighborListPanel.setEnabled(true);
                for (Component c : neighborListPanel1.getComponents()) c.setEnabled(true);
                for (Component c : neighborListPanel2.getComponents()) c.setEnabled(true);
                if(!neighborListPanel.isEnabled()) fichier.changeLieuVisibility('A',true);
                graphPanel1.repaint();
                is2Distancetxt.setText("");
                filtreUnDeuxDistance();
            }
            else{
                selection1 = lieuEvent.get(0);
                selection2 = lieuEvent.get(1);
                jComboBox1.setEnabled(true);
                jLabel13.setText(Character.toString(selection1.getType()));
                jLabel14.setText(selection1.getNomLieu());
                jLabel33.setText(Character.toString(selection2.getType()));
                jLabel35.setText(selection2.getNomLieu());
                for(TLieu l = fichier.getListe(); l !=null ; l = l.getSuivant()){
                    for(TRoute r = l.getTetelisteroutes(); r !=null ; r = r.getSuivant()){
                        r.setRoutePluscourChemin(false);
                    }
                }
                numberPanel.setEnabled(false);
                for (Component c : numberPanel.getComponents()) c.setEnabled(false);
                comparPanel.setEnabled(true);
                for (Component c : comparPanel.getComponents()) c.setEnabled(true);
                neighborListPanel.setEnabled(true);
                for (Component c : neighborListPanel1.getComponents()) c.setEnabled(true);
                for (Component c : neighborListPanel2.getComponents()) c.setEnabled(true);
                comparaison();
                fichier.changeLieuVisibility('A',true);
                graphPanel1.repaint();
                if (fichier.isDeuxDistance(selection1, selection2)) {
                    is2Distancetxt.setText("<html>Les 2 lieux sont à 2-distance <br>de l'un de l'autre</html>");
                } else {
                    is2Distancetxt.setText("<html>Les 2 lieux ne sont pas à 2-distance <br>de l'un de l'autre</html>");
                }
            }
        }
    }
}
